name: Update PixelGen

on:
  workflow_dispatch:
  schedule:
    - cron: '25 10 * * 2'

jobs:
  push_gentoo_to_hub:
    name: Push Midori AI's PixelGen (Gentoo Linux) to Docker Hub
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelgen
          tags: |
            type=raw,value=latest
            type=raw,value=quartz

      - name: Build and push PixelGen Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Cluster-OS/pixelgen_os/
          file: ./Cluster-OS/pixelgen_os/gentoo_dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean up Docker Cache
        run: |
          docker image prune -f
